title: CU Trans Guide
email: anna328p+cutg@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

maps_api_key: AIzaSyBANUiCWRsnISS-MAQlt9YHQ9mTdWdHnKc

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - classifier-reborn

collections:
  entities:
    output: true
  components:
    output: true
  programs:
    output: true

defaults:
  - scope:
      type: entities
    values:
      layout: entity
  - scope:
      type: components
    values:
      layout: component

liquid:
  error_mode: strict
  strict_filters: true

strict_front_matter: true

permalink: /:slugified_categories/:year/:month/:day/:title

lsi: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .direnv/
  - shell.nix
  - default.nix
  - flake.nix
  - flake.lock
